[optimize]
RedrockMobile/CyxbsMobile_iOS pull request #106
Opened 2022-03-31 13:52 UTC by HONEY-SSR

2022-03-31 13:55 UTC, StoveC commented on CyxbsMobile2019_iOS/ClassSchedule/View/TopBarScrollView.m
> +        UIButton *oldBtn = self.weekChooseBtnArray[0];
不建议这么改，这么改会导致新的bug

2022-03-31 13:56 UTC, StoveC commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/Controller/DiscoverViewController.m
> +    for(DiscoverAD *item in self.ADModel.discoverADs.ADs) {
命名不规范，discoverADs是个啥类型？ADs又是啥？

2022-03-31 13:57 UTC, StoveC commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/Controller/DiscoverViewController.m
> +    if(self.oneNewsModel.jwzxNews.news != nil){
jwzxNews 是个啥类型？news又是个啥类型？命名不规范

2022-03-31 13:58 UTC, StoveC commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/DIscover_JWZX/JWZXNewsModel/JWZXNews/JWZXNew/JWZXNew.h
> +
这些属性命名都不规范

2022-03-31 13:58 UTC, StoveC commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/DIscover_JWZX/JWZXNewsModel/JWZXNews/JWZXNew/JWZXNew.h
> +
JWZXNew 这个类也命名不规范

2022-03-31 13:59 UTC, StoveC commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/DIscover_JWZX/JWZXNewsModel/JWZXNews/JWZXNew/JWZXNew.m
> +        self.readCount = dic[@"readCount"];
建议学一手MJExtension

2022-03-31 13:59 UTC, StoveC commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/DIscover_JWZX/JWZXNewsModel/JWZXNews/JWZXNews.h
> +
命名不规范

2022-03-31 14:00 UTC, StoveC commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/DIscover_JWZX/JWZXNewsModel/JWZXNewsModel.h
> +- (void)GET_JWZXPage:(NSUInteger)page success:(void (^)(void))setJWZX;
没有网络请求失败的回调

2022-03-31 14:01 UTC, StoveC commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/DIscover_JWZX/JWZXNewsModel/JWZXNewsModel.m
> +        setJWZX();
一但传入的 setJWZX 为空，你这里就会奔溃，建议 if (setJWZX) { setJWZX(); }

2022-03-31 14:03 UTC, StoveC commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/Discover_AD/DiscoverADBannerView/DiscoverADBannerView.h
> +@property (nonatomic, weak) id <DiscoverADBannerViewDelegate> ssr_delegate;
一般情况下代理直接命名为 delegate 就会了，加个前缀ssr_并没有什么实际的用途吧，看起来还有些怪

2022-03-31 14:05 UTC, StoveC commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/Discover_AD/DiscoverADBannerView/DiscoverADBannerView.m
> +} _DiscoverADBannerViewDelegate;
_DiscoverADBannerViewDelegate 这个结构体，你是用来判断代理是否遵守协议的吧？这样会有个问题，这个结构体是全局变量，是全部 DiscoverADBannerView 实例对象共用的，一但 DiscoverADBannerView 有多个实例对象，你的代码就会出问题。

2022-03-31 14:06 UTC, StoveC commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/Discover_AD/DiscoverADBannerView/DiscoverADBannerView.m
> +- (void)startTimer {
startTimer 的调用时机是啥呢？写一下注射捏～

2022-03-31 14:06 UTC, StoveC commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/Discover_AD/DiscoverADBannerView/DiscoverADBannerView.m
> +- (void)endTimer {
endTimer 的调用时机是啥呢？写一下注射捏～

2022-03-31 14:07 UTC, StoveC commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/Discover_AD/DiscoverADBannerView/DiscoverADBannerView.m
> +- (void)automaticScroll {
automaticScroll 做了什么事？写一下注释捏～

2022-03-31 14:08 UTC, StoveC commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/Discover_AD/DiscoverADBannerView/DiscoverADBannerView.m
> +    self.dataSource = nil;
把代理赋值为空的必要是啥？有这个必要吗？

2022-03-31 14:08 UTC, StoveC commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/Discover_AD/DiscoverADBannerView/DiscoverADBannerView.m
> +
这些代理里面为什么要这么做？注释呢？

2022-03-31 14:10 UTC, StoveC commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/Discover_AD/DiscoverADBannerView/DiscoverADItem/DiscoverADItem.h
> +- (DiscoverADItem *)Default;
Default方法里，你这里貌似只是把图片设置成默认图片吧？Default这种命名一般用于单例，你这样容易导致误会。一般不大写。

2022-03-31 14:12 UTC, StoveC commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/Discover_AD/DiscoverADController/DiscoverADController.m
> +#import "DiscoverADController.h"
那个东西一般不叫广告位，叫banner，也就是说不应该命名为AD，

2022-03-31 14:13 UTC, StoveC commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/Discover_AD/DiscoverADController/DiscoverADController.m
> +    [self.view addSubview:self.ADBannerView];
在 viewWillAppear 里面 addSubview 会导致 viewWillAppear 方法被调用多次，虽然 addSubview 是以最后一次 add为准，但是我不确定你这样是否会有性能上的影响

2022-03-31 14:14 UTC, StoveC commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/Discover_AD/DiscoverADModel/DiscoverADModel.h
> +- (void)GETADsSuccess:(void (^)(void))setModel;
网络请求没有网络请求失败的回调

2022-03-31 14:15 UTC, StoveC commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/Discover_AD/DiscoverADModel/DiscoverADModel.m
> +        setModel();
setModel 为空可能导致奔溃

2022-03-31 14:16 UTC, StoveC commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/Discover_AD/DiscoverADModel/DiscoverADs/DiscoverAD/DiscoverAD.h
> +
命名不规范

2022-03-31 14:16 UTC, StoveC commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/Discover_AD/DiscoverADModel/DiscoverADs/DiscoverADs.h
> +
属性命名不规范

2022-03-31 14:18 UTC, StoveC commented on CyxbsMobile2019_iOS/Tools/Category/NSDate+Day/NSDate+Day.m
>      return  [NSDate date];
这里返回的当前时刻的 NSDate，命名改为 nowdate 貌似会更准确吧？

2022-03-31 14:19 UTC, StoveC commented on CyxbsMobile2019_iOS/Tools/Category/NSDate+Day/NSDate+Day.h
这种类似的扩展，好像已经有第三方库实现过了，掌邮里也已经接入了

2022-03-31 14:20 UTC, StoveC commented on CyxbsMobile2019_iOS/Tools/Category/UIView+Frame/UIView+Frame.m
> +    return CGRectMake(0, 0, self.width, self.height);
这里返回的是 CGRectMake(0, 0, self.width, self.height)，为啥是叫SuperFrame呢？

2022-03-31 14:20 UTC, StoveC commented on CyxbsMobile2019_iOS/Tools/Encapsulation/QuestionSelectView/QuestionButton/QuestionButton.h
> +@property (nonatomic) NSUInteger target;
UIView 有个 tag 属性，你这个 target 属性的用法和 tag 类似吗？

2022-03-31 14:21 UTC, StoveC commented on CyxbsMobile2019_iOS/Tools/Encapsulation/QuestionSelectView/QuestionButton/QuestionButton.h
> +@property (nonatomic, copy) NSString *title;
命名不规范，改为 titleStr 更准确

2022-03-31 14:22 UTC, StoveC commented on CyxbsMobile2019_iOS/Tools/Encapsulation/QuestionSelectView/QuestionSelectView.m
> +} _QuestionSelectViewDelegate;
和 _DiscoverADBannerViewDelegate 有类似的问题吧？

2022-03-31 14:26 UTC, StoveC requested changes
命名的问题挺多，Xcode支持快速地修改命名，希望你还记得怎么用。
还有其它小问题，希望可以仔细对着改一下，有什么地方的评论如果不对，欢迎沟通。 
：）

2022-04-04 09:14 UTC, HONEY-SSR commented on CyxbsMobile2019_iOS/Tools/Category/UIView+Frame/UIView+Frame.m
> +    return CGRectMake(0, 0, self.width, self.height);
假设有一个View，当它的大小跟父控件的大小一致时，并且要完完整整的覆盖这个View。例如contentView在UITableViewCell上的，那么我们如果利用最原始的方法，就会写成:contentView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, self.width, self.height)] 是不是有点麻烦呢

2022-04-04 09:15 UTC, RisingSSR commented on CyxbsMobile2019_iOS/Tools/Category/NSDate+Day/NSDate+Day.h
憋管着玩意，我封着玩的，最重要的是下面的东西

2022-04-04 09:16 UTC, HONEY-SSR commented on CyxbsMobile2019_iOS/Tools/Encapsulation/QuestionSelectView/QuestionButton/QuestionButton.h
> +@property (nonatomic) NSUInteger target;
为了防止某些人要用tag搞事情（我也想过直接用类扩展的）emmm，但是为了让代码可行性更高（可能有人真的要用tag搞其他事（不会吧，不会吧）），我还是思考了许久...

2022-04-04 09:18 UTC, RisingSSR commented on CyxbsMobile2019_iOS/Tools/Encapsulation/QuestionSelectView/QuestionButton/QuestionButton.h
> +@property (nonatomic, copy) NSString *title;
这是个计算属性，不能用titleStr，他不在内存里面...而且我觉得见名知意就好了，不会有人觉得title是Intager属性吧

2022-04-04 12:31 UTC, StoveC commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/DIscover_JWZX/JWZXNewsModel/JWZXNewsModel.h
> +- (void)requestJWZXPage:(NSUInteger)page success:(void (^)(void))setJWZX;
没有请求失败的回调

2022-04-04 12:38 UTC, StoveC commented on CyxbsMobile2019_iOS/Mine/FeedBackCenter/MainPage/Views/CustomView/FeedBackSelectView/FeedBackSelectView.m
> +- (void)initializer {
initializer 是私有方法吧？私有方法建议加上前缀或者后缀，避免有继承自该类的子类重写了私有方法，导致崩溃

2022-04-04 12:53 UTC, StoveC commented on CyxbsMobile2019_iOS/Tools/Encapsulation/QuestionSelectView/QuestionSelectView.m
> +@property (nonatomic, strong) NSArray <__kindof QuestionButton *> *buttons;
NSArray 得用 copy，作为修饰符，不然某些情况下会导致 bug

2022-04-04 12:59 UTC, StoveC commented on CyxbsMobile2019_iOS/Tools/Encapsulation/QuestionSelectView/QuestionSelectView.m
> +        self.gap = [self.delegate gapBetweenButtonsAtQuestionSelectView:self];
这里直接把gap存下来不好。我相信，苹果的tableView，不会只调用一次代理的 numberOfRow 方法，并把 numberOfRow 存下来，不再更新。

我是想说，正如 numberOfRow 的返回值会变一样，你这里的 gap 也可能会变吧？

2022-04-04 13:11 UTC, StoveC approved these changes

2022-04-04 13:48 UTC, RisingSSR commented on CyxbsMobile2019_iOS/Tools/Encapsulation/QuestionSelectView/QuestionSelectView.m
> +        self.gap = [self.delegate gapBetweenButtonsAtQuestionSelectView:self];
以后也许会用到，不过不是现在(*^__^*)

2022-04-04 13:50 UTC, HONEY-SSR commented on CyxbsMobile2019_iOS/Mine/FeedBackCenter/MainPage/Views/CustomView/FeedBackSelectView/FeedBackSelectView.m
> +- (void)initializer {
这个方法就是个自己命名的私有方法，不存在重写这一说法吧...（自己的类掉用自己的initializer啊

2022-04-04 14:18 UTC, Rock-Connotation approved these changes
将commen都解决掉之后再pr吧

2022-04-04 14:18 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/ClassSchedule/View/TopBarScrollView.m
> +        float duration = abs(newIndex.intValue-0)*0.3;
上面已经用到了oldIndex（第353行），为什么这里要用0而不是继续用oldIndex.intValue呢？

2022-04-04 14:18 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/Controller/DiscoverViewController.m
> +@property (nonatomic, strong)JWZXNewsModel *oneNewsModel;
命名能不能走心点，类都改成JWZXNewsModel了，属性名字还不改

2022-04-04 14:18 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/DIscover_JWZX/JWZXNewsModel/JWZXNews/JWZXNew/JWZXNew.h
> +
类注释放在@interface上面一行，原因已经跟你说过了

2022-04-04 14:18 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/DIscover_JWZX/JWZXNewsModel/JWZXNews/JWZXNew/JWZXNew.h
> +
整个类名以及属性的命名都需要按照规范改一下。
这个类作为Model要有Model的后缀。
属性如果不是为了字典转模型时用KVC，那就在对应属性名后加上数据类型后缀

2022-04-04 14:18 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/DIscover_JWZX/JWZXNewsModel/JWZXNews/JWZXNewsInformation.h
> +
类注释放在@interface上面一行。

2022-04-04 14:18 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/Discover_AD/DiscoverADBannerView/DiscoverADBannerView.m
> +#pragma mark - Lazy
getter、setter方法分开分界。而且懒加载一般都是指的对控件getter方法的重写

2022-04-04 14:18 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/Discover_AD/DiscoverADBannerView/DiscoverADBannerView.m
> +- (void)set_DiscoverADBannerViewDelegate {
用小驼峰命名法

2022-04-04 14:18 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/Discover_AD/DiscoverADBannerView/DiscoverADBannerView.m
> +#pragma mark - Method
方法分界分区之前说了。响应方法放中间，setter、getter放最后

2022-04-04 14:18 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/Discover_AD/DiscoverADBannerView/DiscoverADItem/DiscoverADItem.m
> +
这个分区跟之前是一样问题，改一下

2022-04-04 14:18 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/Discover_AD/DiscoverADController/DiscoverADController.m
> +#pragma mark - Init
其实一般init方法也是属于VC的life cycle里面的

2022-04-04 14:18 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/Discover_AD/DiscoverADController/DiscoverADController.m
> +#pragma mark - Lazy
方法分区调整一下

2022-04-04 14:18 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/Discover_AD/DiscoverADModel/DiscoverADModel.m
> +    if (self.delegate) {
这里倒不如这样self.delegate respondsToSelector:<#(SEL)#>

2022-04-04 14:18 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/Discover_AD/DiscoverADModel/DiscoverADModel.m
> +        // 同理，个数为0啥也不是
那上一个判断直接在一个 if 判断里面 || 一下不是更好

2022-04-04 14:18 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Tools/Encapsulation/QuestionSelectView/QuestionButton/QuestionButton.h
> +@property (nonatomic, copy) NSString *title;
tittle可以是titleLaebl也可以是titleStr。只有一个title很容易模糊

2022-04-04 14:18 UTC, Rock-Connotation approved these changes
将commen都解决掉之后再pr吧

2022-04-04 15:26 UTC, merged

2022-04-05 04:30 UTC, HONEY-SSR commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/Controller/DiscoverViewController.m
> +@property (nonatomic, strong)JWZXNewsModel *oneNewsModel;
历史遗留问题，可改

2022-04-05 04:31 UTC, HONEY-SSR commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/DIscover_JWZX/JWZXNewsModel/JWZXNews/JWZXNew/JWZXNew.h
> +
OK，建议文档也写一下，这个会在之后都进行相关调整

2022-04-05 04:34 UTC, HONEY-SSR commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/DIscover_JWZX/JWZXNewsModel/JWZXNews/JWZXNew/JWZXNew.h
> +
有待商讨具体是否应该对见名知意的类添加后缀（例如在Swift中，只有var和let，比我们这个更难懂）我认为可以有待确定，或是翻看其他工程的源码，借鉴参考。

2022-04-05 04:34 UTC, HONEY-SSR commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/Discover_AD/DiscoverADController/DiscoverADController.m
> +#pragma mark - Init
OK，这个会在之后的解决中得到反馈

2022-04-05 04:37 UTC, HONEY-SSR commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/Discover_AD/DiscoverADModel/DiscoverADModel.m
> +    if (self.delegate) {
见delegateFlags的性能优化，request的只用判断是否有，而optional则需要delegateFlags

2022-04-05 04:39 UTC, HONEY-SSR commented on CyxbsMobile2019_iOS/Discover/Discover_MainPage/Discover_AD/DiscoverADModel/DiscoverADModel.m
> +        // 同理，个数为0啥也不是
不可以，编译器如果会偷懒的话，就会直接执行一个更为简单的表达式，
例如if (((j = i * i * i) < 323) || 1)在部分编译器中，j无法得到值