SystemMessage
RedrockMobile/CyxbsMobile_iOS pull request #118
Opened 2022-04-29 08:15 UTC by HONEY-SSR

消息系统需求

2022-04-29 09:41 UTC, HONEY-SSR commented
接口已屏蔽，pull一次看是否有问题

2022-04-29 09:49 UTC, HONEY-SSR commented
放心review，极低耦合，只需打开一句代码即可看到新需求（目前缺接口）

2022-05-07 07:36 UTC, StoveC requested changes

2022-05-07 07:36 UTC, StoveC commented on CyxbsMobile2019_iOS/Discover/Discover_MineMessage/ActiveMessage_module/View/ActiveMessageCell.m
> +    return (_activeMessageCellMaxHeight < contentHeight ? _activeMessageCellMaxHeight : contentHeight) + 140 + (SCREEN_WIDTH - 2 * 30) * 193.0 / 343.0;
别整这么多魔法数字，很容易让人困惑，加点注释

2022-05-07 07:36 UTC, StoveC commented on CyxbsMobile2019_iOS/Discover/Discover_MineMessage/ActiveMessage_module/ViewController/ActiveMessageVC.m
> +    [cell
你这dequeueReusableCell返回值不会为nil吗？

2022-05-07 07:36 UTC, StoveC commented on CyxbsMobile2019_iOS/Discover/Discover_MineMessage/DiscoverMineMessage_module/DiscoverMineMessageVC.h
> +@end
“mine message that show outside in, use init”，mine ?
“red boll”，boll?
你这英文也不是很好啊，大家英文也不是很好啊，就别用英文注释了吧，，，

2022-05-07 07:36 UTC, StoveC commented on CyxbsMobile2019_iOS/Discover/Discover_MineMessage/SystemMessage_module/View/SystemMessageCell/SystemMessageCell.m
> +        _msgTimeLab = [[UILabel alloc] initWithFrame:CGRectMake(0, 10, 70, 15)];
“CGRectMake(0, 10, 70, 15)” 好多地方都看见你布局是写死的，对图的时候，可能会被视觉的人折磨了。

2022-05-07 07:36 UTC, StoveC commented on CyxbsMobile2019_iOS/Tools/NetWork/HttpTool.m
> +       progress:(nullable void (^)(NSProgress * _Nonnull))progress
以掌邮的实际情况来看，“progress:(nullable void (^)(NSProgress * _Nonnull))progress” 这个参数极大概率是，用不上的，建议加一个没有这个参数的请求

2022-05-07 07:36 UTC, StoveC commented on CyxbsMobile2019_iOS/Tools/NetWork/HttpTool.m
> +        _defaultJSONRequest = AFJSONRequestSerializer.serializer;
（没有代理，我的网络优点问题，这个 comment 好像传不上去，重新贴一下，如有重复，请忽略）
这个 Serializer，以及其它几个 Serializer，这样写会有问题：
考虑到 token 会过期，将来掌邮必然是会在 app 进入前台后刷新token的，也就是解决app长时间停留后台导致token过期的问题。而你这样设计，会导致 token 被刷新后，使用的仍然是旧的token。

2022-05-07 07:36 UTC, StoveC commented on CyxbsMobile2019_iOS/Tools/NetWork/HttpTool.m
> +            self.sessionManager.requestSerializer = self.defaultJSONRequest;
（没有代理，我的网络有点问题，这个 comment 好像传不上去，重新贴一下，如有重复，请忽略）
你这样设计，线程不安全啊，而且又是单例，不好：
考虑开启了多个线程同时进行网络请求，而且，这几个线程网络请求的 requestSerializer 都是不一样的，那么这几个线程的网络请求就会出现问题

2022-05-07 07:36 UTC, StoveC commented on CyxbsMobile2019_iOS/Tools/NetWork/HttpTool.m
> +        _shareTool = [[super allocWithZone:nil] init];
单例设计的有问题

2022-05-07 07:36 UTC, StoveC commented on CyxbsMobile2019_iOS/Marco/CyxbsMobileURL.h
> +
（网络有点问题，如果重复请忽略）
其实 afn 支持设置一个baseURL，然后请求时，只要使用路径就行，比如：
AFHTTPSessionManager *man = [[AFHTTPSessionManager alloc] initWithBaseURL:CyxbsMobileBaseURL_1];
[man GET:@"message-system/user/msgHasRead" ..... ];
感觉好使一些，设计网络请求工具时，可以这么干，有时间可以去了解一下

2022-05-07 07:36 UTC, StoveC commented on CyxbsMobile2019_iOS/Tools/NetWork/HttpTool.m
> +            self.sessionManager.requestSerializer = self.propertyListRequest;
你这样设计，线程不安全啊，而且又是单例，不好：
考虑开启了多个线程同时进行网络请求，而且，这几个线程网络请求的 requestSerializer 都是不一样的，那么这几个线程的网络请求就会出现问题

2022-05-07 07:36 UTC, StoveC commented on CyxbsMobile2019_iOS/Marco/CyxbsMobileURL.h
> +#define MineMessage_PUT_hasRead_API [CyxbsMobileBaseURL_1 stringByAppendingString:@"message-system/user/msgHasRead"]
其实 afn 支持设置一个baseURL，然后请求时，只要使用路径就行，比如：
AFHTTPSessionManager *man = [[AFHTTPSessionManager alloc] initWithBaseURL:CyxbsMobileBaseURL_1];
[man GET:@"message-system/user/msgHasRead" ..... ];
感觉好使一些，设计网络请求工具时，可以这么干，有时间可以去了解一下

2022-05-07 14:13 UTC, HONEY-SSR commented on CyxbsMobile2019_iOS/Discover/Discover_MineMessage/ActiveMessage_module/ViewController/ActiveMessageVC.m
> +    [cell
- (__kindof UITableViewCell *)dequeueReusableCellWithIdentifier:(NSString *)identifier forIndexPath:(NSIndexPath *)indexPath API_AVAILABLE(ios(6.0));

2022-05-07 14:15 UTC, HONEY-SSR commented on CyxbsMobile2019_iOS/Discover/Discover_MineMessage/SystemMessage_module/View/SystemMessageCell/SystemMessageCell.m
> +        _msgTimeLab = [[UILabel alloc] initWithFrame:CGRectMake(0, 10, 70, 15)];
没有，已经对过图了，没关系

2022-05-07 14:16 UTC, HONEY-SSR commented on CyxbsMobile2019_iOS/Tools/NetWork/HttpTool.m
> +       progress:(nullable void (^)(NSProgress * _Nonnull))progress
这个是上传大文件传输，还是得加上，而且加上反正传nil也没关系，af实现我稍微看过了

2022-05-08 06:24 UTC, ZhongWentao2002 approved these changes

2022-05-08 06:32 UTC, StoveC approved these changes

2022-05-08 06:32 UTC, merged