Origin/feature/school bus
RedrockMobile/CyxbsMobile_iOS pull request #121
Opened 2022-05-21 08:21 UTC by ptyou-u

2022-05-21 09:54 UTC, Rock-Connotation approved these changes

2022-05-21 15:36 UTC, HONEY-SSR commented on CyxbsMobile2019_iOS/Discover/Discover_SchoolBus/Controller/BusGuideViewController.m
> +    self.titleColor = [UIColor colorNamed:@"21_49_91"];
请用新的第三方库，请自己合并

2022-05-21 15:38 UTC, HONEY-SSR commented on CyxbsMobile2019_iOS/Discover/Discover_SchoolBus/Controller/BusGuideViewController.m
> +        view.backgroundColor = [UIColor colorNamed:@"Whiter&Black"];
颜色问题（颜色问题将用：color给你标出来，更改后再推）

2022-05-21 15:39 UTC, HONEY-SSR requested changes
颜色问题先更改，UI是有问题的，反正我已经帮你发版了，自己看着办(6.3.5(2))

2022-06-05 14:13 UTC, HONEY-SSR approved these changes

2022-06-05 14:13 UTC, merged