Feature/mine and center test
RedrockMobile/CyxbsMobile_iOS pull request #183
Opened 2024-03-07 10:29 UTC by Max-Xu2004

2024-03-10 04:07 UTC, RisingSSR commented on CyxbsMobile2019_iOS/Center/Activity/Activity_DetailPage/VC/ActivityDetailVC.swift
不允许使用UIScreen.main.bounds
请用组件库

2024-03-10 04:17 UTC, RisingSSR commented on CyxbsMobile2019_iOS/Center/Attitude/ExpressDetailPage/Model/items/ExpressPickGetItem.m
这里去写一个NSDictionary的扩展吧
这样的使用方式会导致数据崩溃
[(NSNumber *)valueArray[i] longValue]
参考扩展：
```Objective-C
@interface NSDictionary (CyxbsAddition)
- (NSIntager) cm_intagerValueForKey:(NSString *)key;
@end
@implimentation
- (NSIntager) cm_intagerValueForKey:(NSString *)key {
    id value = [self objectForKey:key];
    if ([key isKindOfClass:[NSNumber class]]) {
        return [(NSNumber *)value longValue];
    }
if ([key isKindOfClass:[NSString class]]) {
        // 处理@“123”情况
    }
...
// 处理其他情况，请自己百度，在组件库中书写
// 组件库的技术需求单独Commit，不要混乱，CR时备注技术需求的SHA-1
}

2024-03-10 04:17 UTC, RisingSSR commented on CyxbsMobile2019_iOS/Center/Attitude/ExpressDetailPage/Model/items/ExpressPickPutItem.m
请新增技术需求

2024-03-10 04:24 UTC, RisingSSR requested changes
1. 需要新增Addition技术需求
2. 不要使用GPT提供的UIScreen.main等代码
> 再看到一次，就别想发版，改完为止！
3. 可以使用Masonry和SnapKit
> 我需要看到你代码中有明确的UI绘制和数据的分开书写
4. 架构规范，MVC、MVVM、MVP各用各的，不要混着用
5. 减少使用SCREEN_WIDTH等根据window生成的宽高
> 应该改为使用父对象来决定宽高，用以适配iPad和Vision Pro
6. 对于原有技术需求，应产生技术文档，文档呢？
7. 对于项目需求，产生项目文档，请整理过往你自己的项目文档。

2024-03-10 04:28 UTC, RisingSSR commented
请自行解决冲突，学习并使用SourceTree。
1. 技术需求排期: 3.10 - 3.13
2. 项目修复排期: 3.10 - 3.14
3. REVIEW时间: 3.15

如果我没有看到你的进步，就别再写项目了
不要使用GPT，请自己思考逻辑

2024-03-22 03:13 UTC, Rock-Connotation commented on Constants/NSDictionaryExtension/NSDictionaryExtension.m
> +    if ([value isKindOfClass:[NSNumber class]]) {
NSNumber 和 NSString 都有 integerValue 这个方法。不用这么麻烦
 if ([value isKindOfClass:[NSString class]] || [value isKindOfClass:[NSNumber class]]) {
            return [value integerValue];
        }

2024-03-22 03:14 UTC, Rock-Connotation commented on Constants/NSDictionaryExtension/NSDictionaryExtension.m
> +- (int)cm_intValueForKey:(id)key {
同上

2024-03-22 03:15 UTC, Rock-Connotation commented on Constants/NSDictionaryExtension/NSDictionaryExtension.m
> +    id value = [self notNullValueForKey:key];
同上

2024-03-22 03:43 UTC, Rock-Connotation commented on Constants/NSDictionaryExtension/NSDictionaryExtension.m
> +- (float)cm_floatValueForKey:(id)key {
string 和 number 也都有 footValue 方法，直接调就行了

2024-03-22 03:46 UTC, Rock-Connotation commented on Constants/NSDictionaryExtension/NSDictionaryExtension.m
> +        return nil;
这个函数的作用是获取非 null 值，为什么会返回 nil

2024-03-22 03:51 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Center/Activity/Activity_MainPage/VC/ActivityCollectionVC.swift
> +        activitiesModel.requestNoticeboardActivities(activityType: activityTypeString) { activities in
activityTypeString 存在为 nil 的情况，检查一下 requestNoticeboardActivities 方法内有没有对应的判断处理。没有的话 nil 可不可能引起异常

2024-03-22 03:58 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Center/Activity/Activity_MainPage/View/ActivityTopView.swift
>      lazy var backButton: UIButton = {
backButton 是在一开始就会直接用的，不需要使用懒加载。
另外为什么属性是在方法下面，很奇怪。一般来说是需要先看到类的属性，这样方便了解类里面有什么东西

2024-03-22 04:17 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Center/Activity/Activity_MainPage/View/ActivityTopView.swift
>          self.backButton.snp.makeConstraints { make in
swift 中一般属性都不用 self.xxx。可以直接写 backButton.snp.makeConstraints { 
只是建议提醒，这里可以不用改

2024-03-22 04:18 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Center/Attitude/ExpressDetailPage/Controller/ExpressDetailPageVC.m
> +@property (nonatomic, strong) ExpressPickGetModel *getDetailModel;
直接 detailModel 就行了，注意一下命名规范。

2024-03-22 04:21 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Center/Attitude/ExpressDetailPage/Controller/ExpressDetailPageVC.m
> +                cell.gradientView.frame = CGRectMake(0, 0, gradientWidth, cell.bounds.size.height);
这个代码的作用是什么？动画结束后 cell.gradientView.frame  就已经是 0, 0, gradientWidth, cell.bounds.size.height。不需要在 completion 里面重复吧？

2024-03-22 04:23 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Center/Attitude/ExpressDetailPage/Controller/ExpressDetailPageVC.m
> +        if (cell.titleLab.text == self.votedChoice) {
这里都是调的 cell 的方法，为什么不把 votedChoice 传给 cell，让 cell 内部去判断处理。vc 不需要知道这些事情

2024-03-22 04:27 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Center/Attitude/ExpressDetailPage/Controller/ExpressDetailPageVC.m
> +        if (![self.votedChoice isEqualToString:@""]) {
如果 votedChoice 是 nil，这里的 if 语句得到的也是 true。加上判空条件

2024-03-22 04:30 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Center/Attitude/ExpressDetailPage/Controller/ExpressDetailPageVC.m
> +        if (![self.votedChoice isEqualToString:@""]) {
另外 votedChoice 在这个 if 语句中也没看到使用，为什么把它作为判断条件？如果是用于标识的话，以后可以让后端专门传一个或者本地自己创建一个用于标识的 key

2024-03-22 04:31 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Center/Attitude/ExpressDetailPage/Controller/ExpressDetailPageVC.m
> +    if (![self.votedChoice isEqualToString:@""]) {
同，这里 votedChoice 为 nil 得到的也是真
如果用于标识是否已经投票，创建一个 bool 属性去专门作为标识

2024-03-22 04:32 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Center/Attitude/ExpressDetailPage/Controller/ExpressDetailPageVC.m
> +//            [self.view removeAllSubviews];
不用的代码提交时就删了

2024-03-22 04:32 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Center/Attitude/ExpressDetailPage/Controller/ExpressDetailPageVC.m
> +    //        [self.view removeAllSubviews];
不用的代码删掉

2024-03-22 04:34 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Center/Attitude/ExpressDetailPage/Model/ExpressPickGetModel.m
> +            NSLog(@"百分比:%@",model.percentStrArray);
log 是用于调试的话，提交时可以删掉

2024-03-22 04:35 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Center/Attitude/ExpressDetailPage/Model/ExpressPickPutModel.m
> +//    NSDictionary *params = @{
无用代码删掉

2024-03-22 04:41 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Mine/StampCenter/StampCenter_MainPage/Controller/StampCenterVC.m
>      }
这里使用 else if

2024-03-22 04:42 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Mine/StampCenter/StampCenter_MainPage/Views/Cell/TableViewVells/TaskTableViewCell/TaskTableViewCell.m
> +- (UILabel *)mainLabel{
属性的 getter 方法放在所有方法后面

2024-03-22 05:00 UTC, Rock-Connotation requested changes
主要一些细节问题，两个小时左右就可以改完了

2024-03-22 05:00 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Mine/StampCenter/StampCenter_MainPage/Views/Cell/TableViewVells/TaskTableViewCell/TaskTableViewCell.m
> +- (void)test:(GotoButton *)sender{
方法命名跟要做的事贴切一些

2024-03-22 05:00 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Mine/StampCenter/StampCenter_MainPage/Views/Cell/TableViewVells/TaskTableViewCell/TaskTableViewCell.m
> +    if ([sender.target isEqualToString:@"斐然成章"]) {
这里设置枚举管理好一些

2024-03-22 05:00 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Mine/StampCenter/StampCenter_MainPage/Views/Cell/TableViewVells/TaskTableViewCellWithProgress/TaskTableViewCellWithProgress.m
> +    }else {
} else {，两边都要空格

2024-03-22 05:00 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/MineMainPage/PersonalMainPage/PMPPrimaryController/PMPSecondaryController/EditMyInformation/View/MineEditTextField.m
> +     固定展示的姓名、学号等内容，因此默认设置这个TextField不再可被用户交互*/
不可交互就直接用 label 展示

2024-03-22 05:00 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/MineMainPage/View/MineTopBlurView.m
> +    //++++++++++++++++++添加姓名label++++++++++++++++++++  Begain
改成属性、懒加载初始化。把这种奇怪的问题删了

2024-03-22 05:00 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/MineMainPage/View/MineTopBlurView.m
> +//- (void)addBlogBtn {
不要的都删了

2024-03-22 05:00 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Tools/Encapsulation/MXBackButton/MXBackButton.swift
> +    private var isAutoHotspotExpand: Bool?
这个是不可变的，不用可选值，改成 let

2024-03-22 05:00 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Tools/Encapsulation/MXBackButton/MXBackButton.swift
> +        var top: CGFloat?
没必要可选值，直接 var top = 0就可以了

2024-03-22 05:00 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Tools/Encapsulation/MXBackButton/MXBackButton.swift
> +        if(isAutoHotspotExpand ?? false) {
使用 guard 语句提前返回
guard isAutoHotspotExpand else { return  super.point(inside: point, with: event) }

2024-03-22 16:07 UTC, RisingSSR approved these changes

2024-03-24 08:57 UTC, Max-Xu2004 commented on CyxbsMobile2019_iOS/Center/Activity/Activity_MainPage/VC/ActivityCollectionVC.swift
> +        activitiesModel.requestNoticeboardActivities(activityType: activityTypeString) { activities in
这个网络请求的activityType参数可以为nil，不会引起异常

2024-03-24 09:09 UTC, Max-Xu2004 commented on CyxbsMobile2019_iOS/Center/Activity/Activity_MainPage/View/ActivityTopView.swift
>      lazy var backButton: UIButton = {
已改进，感谢指出

2024-03-31 13:33 UTC, Max-Xu2004 commented on CyxbsMobile2019_iOS/Mine/StampCenter/StampCenter_MainPage/Views/Cell/TableViewVells/TaskTableViewCell/TaskTableViewCell.m
> +    if ([sender.target isEqualToString:@"斐然成章"]) {
个人认为枚举管理的话可能代码量有点大，可读性也不太好，因此我的想法是用字典将按钮的目标字符串映射到通知名称
NSDictionary *targetToNotification = @{
        @"斐然成章": @"jumpToReleaseDynamic",
        @"绑定志愿者账号": @"jumpToZhiyuan",
        @"完善个人信息": @"jumpToProfile",
        @"发表一次表态": @"jumpToAttitude",
        @"使用美食板块": @"jumpToFood",
        @"使用一次没课约": @"jumpToWeDate",
        @"在表态广场完成一次表态": @"jumpToProfile",
        @"今日打卡": @"checkInToday",
        @"参加一次活动": @"jumpToActivity"
    };
    NSString *notificationName = targetToNotification[sender.target];
    if (notificationName) {
        [[NSNotificationCenter defaultCenter] postNotificationName:notificationName object:nil];
    } else {
        [[NSNotificationCenter defaultCenter] postNotificationName:@"jumpToProfile" object:nil];
    }

2024-03-31 13:39 UTC, Max-Xu2004 commented on CyxbsMobile2019_iOS/Mine/StampCenter/StampCenter_MainPage/Views/Cell/TableViewVells/TaskTableViewCell/TaskTableViewCell.m
> +- (void)test:(GotoButton *)sender{
已修改

2024-03-31 13:39 UTC, Max-Xu2004 commented on CyxbsMobile2019_iOS/Mine/StampCenter/StampCenter_MainPage/Views/Cell/TableViewVells/TaskTableViewCell/TaskTableViewCell.m
> +- (UILabel *)mainLabel{
已修改

2024-03-31 13:39 UTC, Max-Xu2004 commented on CyxbsMobile2019_iOS/Mine/StampCenter/StampCenter_MainPage/Controller/StampCenterVC.m
>      }
已修改

2024-03-31 13:39 UTC, Max-Xu2004 commented on CyxbsMobile2019_iOS/Center/Attitude/ExpressDetailPage/Model/ExpressPickPutModel.m
> +//    NSDictionary *params = @{
已修改

2024-03-31 13:40 UTC, Max-Xu2004 commented on CyxbsMobile2019_iOS/Center/Attitude/ExpressDetailPage/Controller/ExpressDetailPageVC.m
> +//            [self.view removeAllSubviews];
已修改

2024-03-31 13:40 UTC, Max-Xu2004 commented on CyxbsMobile2019_iOS/Center/Attitude/ExpressDetailPage/Controller/ExpressDetailPageVC.m
> +    //        [self.view removeAllSubviews];
已修改

2024-03-31 13:41 UTC, Max-Xu2004 commented on CyxbsMobile2019_iOS/Center/Attitude/ExpressDetailPage/Controller/ExpressDetailPageVC.m
> +        if (![self.votedChoice isEqualToString:@""]) {
添加了标识的BOOL变量

2024-03-31 13:42 UTC, Max-Xu2004 commented on CyxbsMobile2019_iOS/Center/Attitude/ExpressDetailPage/Controller/ExpressDetailPageVC.m
> +        if (cell.titleLab.text == self.votedChoice) {
改动将动画相关逻辑交给cell处理

2024-03-31 13:42 UTC, Max-Xu2004 commented on CyxbsMobile2019_iOS/Center/Attitude/ExpressDetailPage/Controller/ExpressDetailPageVC.m
> +@property (nonatomic, strong) ExpressPickGetModel *getDetailModel;
已规范表态（attitude）版块变量名和类名

2024-03-31 13:42 UTC, Max-Xu2004 commented on CyxbsMobile2019_iOS/Center/Attitude/ExpressDetailPage/Controller/ExpressDetailPageVC.m
> +                cell.gradientView.frame = CGRectMake(0, 0, gradientWidth, cell.bounds.size.height);
同下

2024-03-31 13:44 UTC, Max-Xu2004 commented on CyxbsMobile2019_iOS/Center/Attitude/ExpressDetailPage/Model/ExpressPickGetModel.m
> +            NSLog(@"百分比:%@",model.percentStrArray);
还在测试是否有bug，暂时保留

2024-03-31 13:48 UTC, Max-Xu2004 commented on CyxbsMobile2019_iOS/MineMainPage/View/MineTopBlurView.m
> +//- (void)addBlogBtn {
已修改

2024-04-01 15:52 UTC, Rock-Connotation reviewed
还有点小问题，辛苦再改改

2024-04-01 15:52 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Center/Attitude/ExpressDetailPage/Controller/ExpressDetailPageVC.m
> +@property (nonatomic, strong) NSArray *percentNumArray;
arrary 用 copy 去修饰。如果不太理解的话可以去搜索  copy 关键字的含义以及深浅拷贝

2024-04-01 15:52 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Center/Attitude/ExpressDetailPage/Controller/ExpressDetailPageVC.m
> +@property (nonatomic, strong) NSArray *percentNumArray;
如果希望数组是可变的，就用 mutableArrary。另外这里希望是 NSNumber 类型的数组，可以这样写去约束存储的类型
@property (nonatomic, copy) NSArray<NSNumber *>* percentNumArray

2024-04-01 15:52 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Center/Attitude/ExpressDetailPage/View/ExpressDetailCell.m
> +- (void)layoutSubviews {
为什么在 layoutSubview 里面添加 subView

2024-04-01 15:52 UTC, Rock-Connotation commented on CyxbsMobile2019_iOS/Center/Attitude/ExpressDetailPage/View/ExpressDetailCell.m
> +        [self.checkImage removeFromSuperview];
移除视图的操作放在 completation 的 block 里面做

2024-04-02 08:21 UTC, Max-Xu2004 commented on CyxbsMobile2019_iOS/Center/Attitude/ExpressDetailPage/View/ExpressDetailCell.m
> +- (void)layoutSubviews {
这个是因为之前gradientView的高度设置为self.bounds.size.height，在initWithStyle中添加会导致高度为0，这次修改为写死高度80

2024-04-02 08:22 UTC, Max-Xu2004 commented on CyxbsMobile2019_iOS/Center/Attitude/ExpressDetailPage/Controller/ExpressDetailPageVC.m
> +@property (nonatomic, strong) NSArray *percentNumArray;
感谢指正，最近都是swift用的多，oc的基础知识确实有些遗忘了

2024-04-02 08:22 UTC, Max-Xu2004 commented on CyxbsMobile2019_iOS/Center/Attitude/ExpressDetailPage/View/ExpressDetailCell.m
> +        [self.checkImage removeFromSuperview];
已修改

2024-04-17 15:40 UTC, Rock-Connotation requested changes

2024-04-17 15:40 UTC, Rock-Connotation commented on TabBar/CustomNavigationController.swift
> +        default:
switch 不要有 default，这样的话一个枚举中有新增 case 时，在使用的地方就不会被忽略掉，更好维护一些

2024-04-17 15:40 UTC, Rock-Connotation commented on TabBar/CustomNavigationController.swift
> +        if operation == .pop {
提前返回用 guard，这里也可以直接使用三目运算符

2024-04-17 15:40 UTC, Rock-Connotation commented on TabBar/CustomNavigationController.swift
> +        if animationController is PopAnimation {
提前返回同上

2024-04-18 15:25 UTC, Rock-Connotation requested changes

2024-04-18 15:25 UTC, Rock-Connotation commented on TabBar/CustomNavigationController.swift
> +
case .possible, .failed:
            break

2024-04-18 15:25 UTC, Rock-Connotation commented on TabBar/CustomNavigationController.swift
> +        @unknown default:
不要 default。你把每个 case 都用到了，就不会有 default了

2024-04-18 15:40 UTC, Rock-Connotation approved these changes

2024-04-19 15:12 UTC, iced2020 approved these changes

2024-04-20 11:54 UTC, merged